### ISSUE TITLE
Doesn't work with any LLM tested

### ISSUE THREAD

**Issue by Djanghost** [esciron/ComfyUI-HunyuanVideoWrapper-Extended#1]
![Capture d'écran 2024-12-10 183155](https://github.com/user-attachments/assets/dcb17833-a5d4-4bf7-ada4-d623827faa1b)

I've tested it on several models using the method you give in your description, but here's the error message I get every time.

**Comment by esciron** [comment]
The model has to be llama, llava or mllama model_type.

**Comment by Djanghost** [comment]
Thanks
