### ISSUE TITLE
If possible, I hope to use nemo 12b, but now it seems that it only supports llama?

### ISSUE THREAD

**Issue by win10ogod** [esciron/ComfyUI-HunyuanVideoWrapper-Extended#2]
If possible, I hope to use nemo 12b, but now it seems that it only supports llama?

**Comment by esciron** [comment]
I'm gonna try to add mistral support, but only in the stable version: https://github.com/esciron/ComfyUI-HunyuanVideoWrapper-Extended/tree/stable
As I don't intend to match the development updates of the original wrapper.
It supports llama, llava and mllama model_type.

Mistral architecture added and working.
